apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jgm75weyv-go 
  janus-idp.io/tekton: jgm75weyv-go
  backstage.io/kubernetes-id: jgm75weyv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jgm75weyv-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml