apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jgm75weyv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jgm75weyv-go 
  name: jgm75weyv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jgm75weyv-go 
